# Generated by Django 2.0.2 on 2018-02-16 16:48

import data.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_x', models.FloatField()),
                ('loc_y', models.FloatField()),
                ('fs', models.FloatField()),
                ('dt', models.FloatField()),
                ('fc', models.FloatField()),
                ('agc', models.FloatField()),
                ('psd', models.ImageField(upload_to=data.models.user_directory_path)),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 2, 16, 16, 48, 41, 107846, tzinfo=utc))),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
