# Generated by Django 2.0.2 on 2018-02-16 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20180216_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 17, 23, 36, 800570, tzinfo=utc)),
        ),
    ]
