# Generated by Django 2.0.2 on 2018-02-16 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20180216_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 16, 17, 34, 59, 699207, tzinfo=utc)),
        ),
    ]
