# Generated by Django 2.0.2 on 2018-02-27 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20180227_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='agc',
            new_name='gain',
        ),
        migrations.RemoveField(
            model_name='data',
            name='psd',
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 8, 18, 59, 467144, tzinfo=utc)),
        ),
    ]
