# Generated by Django 2.0.2 on 2018-02-27 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20180227_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sdr_id',
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 27, 8, 33, 59, 258526, tzinfo=utc)),
        ),
    ]
