# Generated by Django 2.0.2 on 2018-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdrpub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdr',
            name='id',
        ),
        migrations.AddField(
            model_name='sdr',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sdr',
            name='ip',
            field=models.GenericIPAddressField(primary_key=True, serialize=False),
        ),
    ]
